name: Issue 956

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: php:8.1-fpm-bullseye
    env:
      IPE_VERSION: 2.3.5
    steps:
      - name: Download install-php-extensions v.${{ env.IPE_VERSION }}
        run: curl -sSLf -o /usr/local/bin/install-php-extensions https://github.com/mlocati/docker-php-extension-installer/releases/download/$IPE_VERSION/install-php-extensions
      - name: Make install-php-extensions executable
        run: chmod +x /usr/local/bin/install-php-extensions
      - name: Install extensions
        run: install-php-extensions pdo_mysql redis sockets zip intl
      - name: Inspect extensions
        run: |
          php --ri pdo_mysql
          php --ri redis
          php --ri sockets
          php --ri zip
          php --ri intl
